# Generated by Django 5.1 on 2024-08-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_created_at_remove_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product_images/placeholder.jpg', upload_to='product_images/'),
        ),
    ]
